-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: [--ignore=E501, --in-place]
    -   id: flake8
        args: ["--ignore=W504,E501"]

-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: f3dfe379d2ea341c6cf54d926d4585b35dea9251
    hooks:
    -   id: reorder-python-imports
        files: .*\.py$
